version: '3.9'

services:
  main-app:
    container_name: main-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory server_application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      ../.env
    volumes:
      - ../app:/app
    ports:
      - ${API_PORT}:8000
  bot:
    container_name: bot
    build:
      context: ..
      dockerfile: Dockerfile
    command: "python3 ./bot_application/main.py"
    env_file:
      ../.env
    volumes:
      - ../app:/app
