name: discord-connections-example

services:
  main-app:
    container_name: main-app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory application.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      ../.env
    volumes:
      - ../app:/app
    ports:
      - ${API_PORT}:8000
    networks:
      - backend
      - db
    depends_on:
      kafka:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 50m
  bot:
    container_name: bot
    build:
      context: ..
      dockerfile: Dockerfile
    command: "python3 ./application/bot/main.py"
    env_file:
      ../.env
    volumes:
      - ../app:/app
    networks:
      - backend
    depends_on:
      kafka:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 50m
  updater:
    container_name: updater
    build:
      context: ..
      dockerfile: Dockerfile
    command: "python3 application/updater/main.py"
    env_file:
      ../.env
    volumes:
      - ../app:/app
    networks:
      - backend
      - db
    depends_on:
      kafka:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: 50m


networks:
  db:
    external: true
  backend:
    external: true